name: Docker (proxy)

on:
  push:
    branches: ["main"]
    paths:
      - proxy/**
  pull_request:
    branches: ["main"]
    paths:
      - proxy/**

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/base.yml
    with:
      service: proxy
      context: proxy/
      test-command: "docker compose run --entrypoint 'nginx -t' proxy"
