name: Docker (server)

on:
  push:
    branches: ["main"]
    paths:
      - server/**
  pull_request:
    branches: ["main"]
    paths:
      - server/**

jobs:
  build:
    uses: ./.github/workflows/docker-build-reusable.yml
    with:
      service: server
      context: server/
      test-command: "mkdir -p server/db/ && make test"
